### PR TITLE
Add GIF of animation to README

### LINKED ISSUE #5: Add demo GIF to the README
Just capture the animation of the landing page and add the GIF in the README file.

### PR DESCRIPTION
**Pull request by jkaan**
Fixes #5

### CODE REVIEW

**Review by Kvaibhav01 — CHANGES_REQUESTED** [review]
The GIF is too short. Let all the elements finish the animation and then stop the recording.

**Comment by jkaan** [comment]
@Kvaibhav01 If you could take another look, I think it's perfect now.

**Review by Kvaibhav01 — APPROVED** [review]
Great!

**Comment by Kvaibhav01** [comment]
Let us wait or you can fix this #2 . See my [last comment](https://github.com/Kvaibhav01/Landing-Page-Animation/issues/5#issuecomment-426387305).

**Comment by jkaan** [comment]
@Kvaibhav01 My Illustrator skills are sadly not very good :(.

**Comment by Kvaibhav01** [comment]
@jkaan we just need to update the font now. See [this](https://github.com/Kvaibhav01/Landing-Page-Animation/pull/6#pullrequestreview-160864301).

**Pull request merged**
